// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXurWCKWE_w33ZZ4Ju3ZZq-6-LTyNRfYs',
    appId: '1:613539779199:web:2098b780fc9facb300254a',
    messagingSenderId: '613539779199',
    projectId: 'taxi-app-eb3a5',
    authDomain: 'taxi-app-eb3a5.firebaseapp.com',
    storageBucket: 'taxi-app-eb3a5.firebasestorage.app',
    measurementId: 'G-P6X86XZCT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYXlmZFYI5eIAVHK7YHarbDeowLTRZ24',
    appId: '1:613539779199:android:98ced41691bdb31100254a',
    messagingSenderId: '613539779199',
    projectId: 'taxi-app-eb3a5',
    storageBucket: 'taxi-app-eb3a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4dJp6c5LAxQ9LK1FoEtaXPceCDvp7vU',
    appId: '1:613539779199:ios:277275cf894df9e200254a',
    messagingSenderId: '613539779199',
    projectId: 'taxi-app-eb3a5',
    storageBucket: 'taxi-app-eb3a5.firebasestorage.app',
    iosBundleId: 'com.vanzylarno.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4dJp6c5LAxQ9LK1FoEtaXPceCDvp7vU',
    appId: '1:613539779199:ios:277275cf894df9e200254a',
    messagingSenderId: '613539779199',
    projectId: 'taxi-app-eb3a5',
    storageBucket: 'taxi-app-eb3a5.firebasestorage.app',
    iosBundleId: 'com.vanzylarno.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXurWCKWE_w33ZZ4Ju3ZZq-6-LTyNRfYs',
    appId: '1:613539779199:web:81d405d8b118be2100254a',
    messagingSenderId: '613539779199',
    projectId: 'taxi-app-eb3a5',
    authDomain: 'taxi-app-eb3a5.firebaseapp.com',
    storageBucket: 'taxi-app-eb3a5.firebasestorage.app',
    measurementId: 'G-ZFBXCB6LHD',
  );
}
